name: Discloud API Action

on: [push]

jobs:
  discloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Discloud API Action
        # Pin to a specific commit for stability
        uses: marco-quicula/discloud-api-action@988e5ee043301812312ebb719ee1568d74edb75d
        with:
          # API token for authentication
          discloud_api_token: ${{ secrets.DISCLOUD_API_TOKEN }}
          # Command to be executed. Supported commands: userinfo, delete, status, upload, commit
          command: upload
          # Application ID. Required for the following commands: delete, status, commit. Can contain the value 'all' for the following commands: delete, status
          appId: # optional
          # File (.zip) to be uploaded. Required for the following commands: upload, commit
          file: # optional
          # Action to be taken if the application is already active. Required for the following command: upload
          actionIfExists: # optional, default is ERROR
